[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103C8"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "relocation-model=static",
    "-C", "target-cpu=cortex-m3",
]

[target.'cfg(all())']
rustflags = [
  "--cfg", "no_test",
]
